import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'

type User = { id: string; email: string; displayName: string }
type AuthResponse = { token: string; user: User }
type Tree = { totalGp: number; todayGp: number; currentStreak: number; longestStreak: number; level: number; stage: string; levelStartGp: number; nextLevelGp: number | null; todayHabits: string[]; unlockedAchievements: string[]; season: string }
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8082/api'
const habits = [{ id: 'water', icon: '💧', label: 'Water', detail: 'Roots & soil', points: 10 }, { id: 'exercise', icon: '💪', label: 'Exercise', detail: 'Trunk & strength', points: 20 }, { id: 'learning', icon: '📚', label: 'Learning', detail: 'Branches & canopy', points: 15 }, { id: 'sleep', icon: '😴', label: 'Sleep', detail: 'Leaves & recovery', points: 20 }, { id: 'meditation', icon: '🧘', label: 'Meditate', detail: 'Flowers & calm', points: 10 }, { id: 'mood', icon: '😊', label: 'Positive mood', detail: 'Wildlife & joy', points: 10 }]
async function api<T>(path: string, options: RequestInit = {}, token?: string): Promise<T> { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.message ?? 'Something went wrong.') } return response.status === 204 ? undefined as T : response.json() }

export default function App() {
  const [token, setToken] = useState(() => localStorage.getItem('mindmirror_token') ?? ''), [user, setUser] = useState<User | null>(null), [tree, setTree] = useState<Tree | null>(null), [register, setRegister] = useState(true), [busy, setBusy] = useState(Boolean(token)), [message, setMessage] = useState('')
  useEffect(() => { if (!token) return; Promise.all([api<User>('/auth/me', {}, token), api<Tree>('/tree', {}, token)]).then(([u, t]) => { setUser(u); setTree(t) }).catch(() => { localStorage.removeItem('mindmirror_token'); setToken('') }).finally(() => setBusy(false)) }, [token])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); const payload = register ? { displayName: form.get('displayName'), email: form.get('email'), password: form.get('password') } : { email: form.get('email'), password: form.get('password') }; try { const result = await api<AuthResponse>(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(payload) }); localStorage.setItem('mindmirror_token', result.token); setToken(result.token); setUser(result.user) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to continue.') } finally { setBusy(false) } }
  async function toggle(id: string) { setBusy(true); try { setTree(await api<Tree>(`/tree/today/${id.toUpperCase()}`, { method: 'POST' }, token)) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to update your tree.') } finally { setBusy(false) } }
  async function logout() { try { await api<void>('/auth/logout', { method: 'POST' }, token) } finally { localStorage.removeItem('mindmirror_token'); setToken(''); setUser(null); setTree(null) } }
  if (busy && token && !tree) return <main className="loading">Tending your Mind Tree…</main>
  if (!user) return <main className="auth-page"><section className="auth-intro"><div className="brand"><span>❧</span> MindMirror</div><div className="intro-copy"><p className="eyebrow">A GENTLER WAY TO GROW</p><h1>Grow a life<br />you’re proud of.</h1><p>Every small act of care helps your Mind Tree take root, stretch upward, and quietly flourish.</p></div><div className="mini-tree"><span className="sun">☀</span><span className="tree">🌳</span></div><p className="intro-foot">No punishment. No broken streaks. Just a living record of your care.</p></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">WELCOME {register ? 'HOME' : 'BACK'}</p><h2>{register ? 'Plant your first seed.' : 'Welcome back.'}</h2><p className="subcopy">{register ? 'Create your space for steady, meaningful growth.' : 'Your tree has been waiting for you.'}</p><form onSubmit={submit}>{register && <label>What should we call you?<input name="displayName" minLength={2} maxLength={80} required /></label>}<label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={8} required /></label>{message && <p className="form-error">{message}</p>}<button className="primary" disabled={busy}>{register ? 'Begin growing' : 'Enter my garden'} →</button></form><p className="switch">{register ? 'Already tending a tree?' : 'New to MindMirror?'} <button type="button" onClick={() => setRegister(!register)}>{register ? 'Sign in' : 'Create an account'}</button></p></div></section></main>
  if (!tree) return null
  const progress = tree.nextLevelGp ? Math.min(100, ((tree.totalGp - tree.levelStartGp) / (tree.nextLevelGp - tree.levelStartGp)) * 100) : 100; const icon = tree.level === 1 ? '🌱' : tree.level === 2 ? '🌿' : tree.level === 5 ? '🌸' : tree.level === 6 ? '🍎' : '🌳'; const has = (key: string) => tree.unlockedAchievements.includes(key)
  return <main className={`dashboard ${tree.season}`}><header><div className="brand"><span>❧</span> MindMirror</div><p>Good to see you, {user.displayName.split(' ')[0]}.</p><button className="text-button" onClick={logout}>Sign out</button></header><section className="dashboard-grid"><div className="tree-card"><div className="tree-top"><div><p className="eyebrow">YOUR MIND TREE · {tree.season.toUpperCase()}</p><h1>{tree.todayGp ? 'Your care is taking root.' : 'Small care, deep roots.'}</h1></div><div className="level">Level {tree.level} <b>{tree.stage}</b></div></div><div className="scene"><span className="cloud cloud-a">☁</span><span className="cloud cloud-b">☁</span>{has('bird') && <span className="wild bird">🐦</span>}{has('butterfly') && <span className="wild butterfly">🦋</span>}{has('fireflies') && <span className="fireflies">✦ ✧ ✦</span>}<span className="main-tree">{icon}</span><div className="ground" /></div><div className="growth"><span>Lifetime growth</span><b>{tree.totalGp} GP <small>{tree.nextLevelGp && `· ${tree.nextLevelGp - tree.totalGp} to next level`}</small></b><div className="progress"><i style={{ width: `${progress}%` }} /></div></div><div className="tree-stats"><span>🔥 {tree.currentStreak} day streak</span><span>🌟 {tree.longestStreak} day best</span><span>Today <b>{tree.todayGp}/85 GP</b></span></div></div><aside className="habit-card"><p className="eyebrow">TODAY’S CARE</p><h2>What feels good today?</h2><p className="subcopy">Each act is saved to your tree. Missing a day only pauses growth.</p><div className="habit-list">{habits.map(h => { const done = tree.todayHabits.includes(h.id); return <button disabled={busy} className={`habit ${done ? 'done' : ''}`} key={h.id} onClick={() => toggle(h.id)}><span className="habit-icon">{h.icon}</span><span><b>{h.label}</b><small>{h.detail}</small></span><em>+{h.points}</em><i>{done ? '✓' : '+'}</i></button> })}</div><p className="encouragement">{tree.todayHabits.length ? 'Lovely. Your tree felt that. ✦' : 'There’s no rush. Start with one small act.'}</p></aside></section><section className="rewards"><div><p className="eyebrow">PERMANENT REWARDS</p><h2>Your living ecosystem</h2></div><div className="reward-list">{[['bird','🐦','7 days'],['nest','🪺','14 days'],['butterfly','🦋','30 days'],['flower-garden','🌸','60 days'],['fireflies','✨','100 days'],['fruits','🍎','180 days'],['golden-leaves','⭐','365 days'],['ancient-guardian','🌳','1000 days']].map(([key, emoji, label]) => <div className={`reward ${has(key) ? 'unlocked' : ''}`} key={key}><span>{emoji}</span><small>{label}</small></div>)}</div></section></main>
}
