import { useEffect, useState } from 'react'
import type { CSSProperties, FormEvent } from 'react'
import './App.css'
import { LifeOperatingSystem } from './components/tree/LifeOperatingSystem'

type User = { id: string; email: string; displayName: string }
type AuthResponse = { token: string; user: User }
type Tree = { currentStreak: number; longestStreak: number; todayHabits: string[]; unlockedAchievements: string[]; season: string }
type Branch = { id: string; parentId: string | null; name: string; icon: string; color: string; position: number }
type Item = { id: string; type: 'GOAL' | 'NOTE' | 'RESOURCE' | 'ACHIEVEMENT' | 'EVENT'; title: string; content: string | null; completed: boolean; dueOn: string | null }
type Workspace = { branch: Branch; items: Item[] }
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:8082/api'
const habits = [{ id: 'water', icon: '💧', label: 'Water' }, { id: 'exercise', icon: '💪', label: 'Exercise' }, { id: 'learning', icon: '📚', label: 'Learning' }, { id: 'sleep', icon: '😴', label: 'Sleep' }, { id: 'meditation', icon: '🧘', label: 'Meditate' }, { id: 'mood', icon: '😊', label: 'Positive mood' }]
const blueprints = [{ id: 'starter', icon: '🌱', name: 'Starter', text: 'A balanced beginning' }, { id: 'student', icon: '🎓', name: 'Student', text: 'Learn with intention' }, { id: 'developer', icon: '💻', name: 'Software Developer', text: 'Build your craft' }, { id: 'entrepreneur', icon: '🚀', name: 'Entrepreneur', text: 'Turn ideas into momentum' }, { id: 'wellness', icon: '🌿', name: 'Wellness', text: 'Care for your whole self' }, { id: 'creative', icon: '🎨', name: 'Creative', text: 'Make room for expression' }, { id: 'finance', icon: '💰', name: 'Finance', text: 'Build a calmer money life' }, { id: 'family', icon: '👨‍👩‍👧', name: 'Family', text: 'Nurture what matters most' }, { id: 'empty', icon: '🌍', name: 'Empty', text: 'Build your own tree' }]
async function api<T>(path: string, options: RequestInit = {}, token?: string): Promise<T> { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail ?? body.message ?? 'Something went wrong.') } return response.status === 204 ? undefined as T : response.json() }

export default function App() {
 const [token, setToken] = useState(() => localStorage.getItem('mindmirror_token') ?? ''), [user, setUser] = useState<User | null>(null), [tree, setTree] = useState<Tree | null>(null), [branches, setBranches] = useState<Branch[]>([]), [workspace, setWorkspace] = useState<Workspace | null>(null), [register, setRegister] = useState(true), [busy, setBusy] = useState(Boolean(token)), [message, setMessage] = useState(''), [blueprint, setBlueprint] = useState<string | null>(null), [newBranch, setNewBranch] = useState(false), [newItem, setNewItem] = useState(false)
 const load = async () => { const [u, t, b] = await Promise.all([api<User>('/auth/me', {}, token), api<Tree>('/tree', {}, token), api<Branch[]>('/branches', {}, token)]); setUser(u); setTree(t); setBranches(b); if (!b.length) setBlueprint('choose') }
 useEffect(() => { if (!token) return; load().catch(() => { localStorage.removeItem('mindmirror_token'); setToken('') }).finally(() => setBusy(false)) }, [token])
 const open = async (id: string) => { setBusy(true); try { setWorkspace(await api<Workspace>(`/branches/${id}/workspace`, {}, token)) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to open branch.') } finally { setBusy(false) } }
 async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); try { const result = await api<AuthResponse>(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(register ? { displayName: form.get('displayName'), email: form.get('email'), password: form.get('password') } : { email: form.get('email'), password: form.get('password') }) }); localStorage.setItem('mindmirror_token', result.token); setToken(result.token); setUser(result.user) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to continue.') } finally { setBusy(false) } }
 async function selectBlueprint(id: string) { setBusy(true); try { setBranches(await api<Branch[]>(`/branches/blueprint/${id}`, { method: 'POST' }, token)); setBlueprint(null) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to create your tree.') } finally { setBusy(false) } }
 async function toggle(id: string) { setBusy(true); try { setTree(await api<Tree>(`/tree/today/${id.toUpperCase()}`, { method: 'POST' }, token)) } finally { setBusy(false) } }
 async function addBranch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { const branch = await api<Branch>('/branches', { method: 'POST', body: JSON.stringify({ name: form.get('name'), icon: form.get('icon') || '🌿', color: '#6f9e63', parentId: workspace?.branch.id ?? null }) }, token); setBranches([...branches, branch]); setNewBranch(false) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to add branch.') } finally { setBusy(false) } }
 async function addWorkspaceItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!workspace) return; const form = new FormData(event.currentTarget); setBusy(true); try { const item = await api<Item>(`/branches/${workspace.branch.id}/items`, { method: 'POST', body: JSON.stringify({ type: form.get('type'), title: form.get('title'), content: form.get('content') || null }) }, token); setWorkspace({ ...workspace, items: [item, ...workspace.items] }); setNewItem(false) } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to save item.') } finally { setBusy(false) } }
 async function toggleItem(item: Item) { if (!workspace) return; const updated = await api<Item>(`/branches/${workspace.branch.id}/items/${item.id}/toggle`, { method: 'POST' }, token); setWorkspace({ ...workspace, items: workspace.items.map(i => i.id === item.id ? updated : i) }) }
 async function logout() { try { await api<void>('/auth/logout', { method: 'POST' }, token) } finally { localStorage.removeItem('mindmirror_token'); setToken(''); setUser(null); setTree(null); setWorkspace(null) } }
 if (busy && token && !tree) return <main className="loading">Tending your Mind Tree…</main>
 if (!user) return <main className="auth-page"><section className="auth-intro"><div className="brand"><span>✧</span> MindMirror</div><div className="intro-copy"><p className="eyebrow">A GENTLER WAY TO GROW</p><h1>Grow a life<br />you’re proud of.</h1><p>Every small act of care helps your Mind Tree take root, stretch upward, and flourish.</p></div><div className="mini-tree"><span className="sun">☀</span><span className="tree">🌳</span></div></section><section className="auth-panel"><div className="auth-card"><p className="eyebrow">WELCOME {register ? 'HOME' : 'BACK'}</p><h2>{register ? 'Plant your first seed.' : 'Welcome back.'}</h2><p className="subcopy">{register ? 'Create your space for steady, meaningful growth.' : 'Your tree has been waiting for you.'}</p><form onSubmit={submit}>{register && <label>What should we call you?<input name="displayName" minLength={2} maxLength={80} required /></label>}<label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" minLength={8} required /></label>{message && <p className="form-error">{message}</p>}<button className="primary" disabled={busy}>{register ? 'Begin growing' : 'Enter my garden'} →</button></form><p className="switch">{register ? 'Already tending a tree?' : 'New to MindMirror?'} <button type="button" onClick={() => setRegister(!register)}>{register ? 'Sign in' : 'Create an account'}</button></p></div></section></main>
 if (!tree) return null
 return <main className={`app ${tree.season}`}>{workspace ? <><header className="app-header"><div className="brand"><span>✦</span> MindMirror</div><span className="hello">Hi, {user.displayName.split(' ')[0]}</span><button className="text-button" onClick={logout}>Sign out</button></header><section className="main-content workspace-page"><Workspace view={workspace} busy={busy} onClose={() => setWorkspace(null)} onAdd={() => setNewItem(true)} onToggle={toggleItem} onAddBranch={() => setNewBranch(true)} /></section></> : <Dashboard tree={tree} onHabit={toggle} busy={busy} branches={branches} onOpen={open} onAddBranch={() => setNewBranch(true)} />}{blueprint && <div className="modal-backdrop"><section className="modal blueprint"><p className="eyebrow">YOUR FIRST CHAPTER</p><h2>Choose a blueprint</h2><p className="subcopy">A starting shape for your life tree. You can change every branch later.</p><div className="blueprints">{blueprints.map(b => <button key={b.id} onClick={() => selectBlueprint(b.id)}><span>{b.icon}</span><b>{b.name}</b><small>{b.text}</small></button>)}</div></section></div>}{newBranch && <div className="modal-backdrop"><form className="modal compact" onSubmit={addBranch}><p className="eyebrow">NEW {workspace ? 'SUB-BRANCH' : 'LIFE AREA'}</p><h2>What matters here?</h2><label>Name<input name="name" autoFocus required maxLength={100} placeholder="e.g. Fitness" /></label><label>Icon<input name="icon" maxLength={16} placeholder="🌿" /></label><div className="modal-actions"><button type="button" onClick={() => setNewBranch(false)}>Cancel</button><button className="primary" disabled={busy}>Create branch</button></div></form></div>}{newItem && <div className="modal-backdrop"><form className="modal compact" onSubmit={addWorkspaceItem}><p className="eyebrow">ADD TO WORKSPACE</p><h2>Capture something meaningful</h2><label>Type<select name="type"><option value="GOAL">Goal</option><option value="NOTE">Note</option><option value="RESOURCE">Resource</option><option value="EVENT">Calendar event</option><option value="ACHIEVEMENT">Achievement</option></select></label><label>Title<input name="title" autoFocus required maxLength={200} /></label><label>Details<textarea name="content" maxLength={10000} /></label><div className="modal-actions"><button type="button" onClick={() => setNewItem(false)}>Cancel</button><button className="primary" disabled={busy}>Save</button></div></form></div>}</main>
}
function Dashboard({ tree, onHabit, busy, branches, onOpen, onAddBranch }: { tree: Tree; onHabit: (id: string) => void; busy: boolean; branches: Branch[]; onOpen: (id: string) => void; onAddBranch: () => void }) {
 return <LifeOperatingSystem tree={tree} branches={branches} busy={busy} onHabit={onHabit} onOpen={onOpen} onAddBranch={onAddBranch} />
 const treeIcon = tree.currentStreak >= 180 ? '🌳' : tree.currentStreak >= 60 ? '🌸' : tree.currentStreak >= 30 ? '🌲' : tree.currentStreak >= 7 ? '🌳' : '🌱'
 const roots = branches.filter(b => !b.parentId)
 const mapPositions = ['north-west', 'north-east', 'west', 'east', 'south-west', 'south-east']
 const [zoom, setZoom] = useState(1)
 const [mapOffset, setMapOffset] = useState({ x: 0, y: 0 })
 const [dragStart, setDragStart] = useState<{ x: number; y: number; offsetX: number; offsetY: number } | null>(null)
 const recenter = () => { setZoom(1); setMapOffset({ x: 0, y: 0 }) }
 return <>
  <section className="map-intro"><div><p className="eyebrow">YOUR LIFE MAP · {tree.season.toUpperCase()}</p><h1>{tree.todayHabits.length ? 'Your world is growing.' : 'Begin at your roots.'}</h1><p>Explore every part of your life as a living landscape. Select a branch pin to enter its workspace.</p></div><div className="map-metrics"><span><b>{tree.currentStreak}</b> day streak</span><span><b>{tree.longestStreak}</b> longest streak</span><span><b>{tree.todayHabits.length}</b> care moments today</span></div></section>
  <section className="life-map" aria-label="Interactive life map"><div className="map-toolbar"><span>⌖ Life map</span><small>Drag to pan · click a branch to explore</small><div><button aria-label="Zoom out" onClick={() => setZoom(value => Math.max(.7, value - .15))}>−</button><button aria-label="Zoom in" onClick={() => setZoom(value => Math.min(1.5, value + .15))}>+</button><button className="recenter" aria-label="Recenter map" onClick={recenter}>⌾</button></div></div><div className="map-world" style={{ transform: `translate(${mapOffset.x}px, ${mapOffset.y}px) scale(${zoom})` }} onPointerDown={event => { if ((event.target as HTMLElement).closest('button')) return; event.currentTarget.setPointerCapture(event.pointerId); setDragStart({ x: event.clientX, y: event.clientY, offsetX: mapOffset.x, offsetY: mapOffset.y }) }} onPointerMove={event => { if (dragStart) setMapOffset({ x: dragStart.offsetX + event.clientX - dragStart.x, y: dragStart.offsetY + event.clientY - dragStart.y }) }} onPointerUp={() => setDragStart(null)}><div className="map-contours contour-one" /><div className="map-contours contour-two" /><div className="map-river" /><div className="map-roots" /><div className="map-trunk" /><div className="map-canopy canopy-a" /><div className="map-canopy canopy-b" /><div className="map-center"><span>{treeIcon}</span><b>My Mind Tree</b><small>{tree.currentStreak ? `${tree.currentStreak}-day rhythm` : 'Ready to grow'}</small></div><svg className="map-paths" viewBox="0 0 1000 560" preserveAspectRatio="none" aria-hidden="true"><path d="M500 305 C350 230 220 150 145 105 M500 305 C650 220 790 130 860 102 M500 305 C340 315 190 305 110 330 M500 305 C660 330 805 315 895 350 M500 305 C380 410 240 470 145 470 M500 305 C625 410 775 460 865 465" /></svg>{roots.map((branch, index) => <button key={branch.id} className={`map-pin ${mapPositions[index % mapPositions.length]}`} style={{ '--pin-color': branch.color } as CSSProperties} onClick={() => onOpen(branch.id)}><span>{branch.icon}</span><b>{branch.name}</b><small>{branches.filter(child => child.parentId === branch.id).length} places</small></button>)}{!roots.length && <p className="map-empty">Add your first life area to begin mapping your world.</p>}</div><div className="map-minimap" onClick={recenter} title="Recenter map"><i /><i /><i /><b /></div><div className="map-legend"><span><i className="legend-dot" /> Life areas</span><span>🌿 Growth is always preserved</span></div></section>
  <section className="dashboard-columns map-dashboard-columns"><div className="panel"><p className="eyebrow">TODAY’S CARE</p><h2>What feels good today?</h2><div className="habit-list">{habits.map(h => { const done = tree.todayHabits.includes(h.id); return <button disabled={busy} className={`habit ${done ? 'done' : ''}`} key={h.id} onClick={() => onHabit(h.id)}><span className="habit-icon">{h.icon}</span><b>{h.label}</b><em>{done ? 'Completed' : 'Care for yourself'}</em><i>{done ? '✓' : '+'}</i></button> })}</div></div><div className="panel map-guide"><p className="eyebrow">MAP GUIDE</p><h2>Your tree, at a glance</h2><p>Each pin is a life area. The paths show their connection to your central Mind Tree.</p><div className="guide-level"><span>{treeIcon}</span><div><b>{tree.currentStreak ? `${tree.currentStreak}-day rhythm` : 'A fresh beginning'}</b><small>{tree.todayHabits.length} care moments completed today</small></div></div></div></section>
 </>
}
function Workspace({ view, busy, onClose, onAdd, onToggle, onAddBranch }: { view: Workspace; busy: boolean; onClose: () => void; onAdd: () => void; onToggle: (item: Item) => void; onAddBranch: () => void }) { const types = ['GOAL', 'NOTE', 'RESOURCE', 'EVENT', 'ACHIEVEMENT'] as const; return <><button className="back" onClick={onClose}>← Back to your tree</button><section className="workspace-head" style={{ borderColor: view.branch.color }}><span>{view.branch.icon}</span><div><p className="eyebrow">BRANCH WORKSPACE</p><h1>{view.branch.name}</h1><p className="subcopy">Goals, notes, resources, milestones, calendar events, and sub-branches all live here.</p></div><button className="secondary" onClick={onAddBranch}>+ Sub-branch</button></section><div className="workspace-actions"><button className="primary" onClick={onAdd}>+ Add item</button></div><section className="workspace-grid">{types.map(type => { const entries = view.items.filter(i => i.type === type); return <div className="workspace-section" key={type}><h2>{({ GOAL: '🎯 Goals', NOTE: '📝 Notes', RESOURCE: '📎 Resources', EVENT: '📅 Calendar & timeline', ACHIEVEMENT: '🏆 Achievements' } as Record<string, string>)[type]}</h2>{entries.length ? entries.map(item => <article className={`item ${item.completed ? 'completed' : ''}`} key={item.id}><button disabled={busy} className="check" onClick={() => onToggle(item)}>{item.completed ? '✓' : '○'}</button><div><b>{item.title}</b>{item.content && <p>{item.content}</p>}</div></article>) : <p className="empty">Nothing here yet — add something when it matters.</p>}</div> })}</section></> }
